# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fingerprint.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Finger import Finger
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnsendttermina = QtWidgets.QPushButton(self.centralwidget)
        self.btnsendttermina.setGeometry(QtCore.QRect(50, 460, 171, 26))
        self.btnsendttermina.setObjectName("btnsendttermina")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 360, 57, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 57, 16))
        self.label_3.setObjectName("label_3")
        self.lineport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineport.setGeometry(QtCore.QRect(10, 180, 113, 26))
        self.lineport.setObjectName("lineport")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 150, 61, 20))
        self.label_4.setObjectName("label_4")
        self.linebrate = QtWidgets.QLineEdit(self.centralwidget)
        self.linebrate.setGeometry(QtCore.QRect(180, 180, 113, 26))
        self.linebrate.setObjectName("linebrate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 250, 131, 16))
        self.label_5.setObjectName("label_5")
        # self.linelocation = QtWidgets.QLineEdit(self.centralwidget)
        # self.linelocation.setGeometry(QtCore.QRect(20, 320, 113, 26))
        # self.linelocation.setObjectName("linelocation")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 57, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 290, 111, 16))
        self.label_7.setObjectName("label_7")
        # self.linepoid = QtWidgets.QLineEdit(self.centralwidget)
        # self.linepoid.setGeometry(QtCore.QRect(180, 320, 113, 26))
        # self.linepoid.setObjectName("linepoid")
        # self.lineamount = QtWidgets.QLineEdit(self.centralwidget)
        # self.lineamount.setGeometry(QtCore.QRect(90, 390, 113, 31))
        # self.lineamount.setObjectName("lineamount")
        self.txtmessage = QtWidgets.QTextEdit(self.centralwidget)
        self.txtmessage.setGeometry(QtCore.QRect(10, 20, 291, 121))
        self.txtmessage.setObjectName("txtmessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FINGERPRINT"))
        self.btnsendttermina.setText(_translate("MainWindow", "Authenticate"))
        # self.label.setText(_translate("MainWindow", "Amount"))
        self.label_3.setText(_translate("MainWindow", "Port"))
        self.label_4.setText(_translate("MainWindow", "b-rate"))
        self.label_5.setText(_translate("MainWindow", "Biometric Authentication"))
       
        self.btnsendttermina.clicked.connect(self.on_click)
        
    def on_click(self):
        self.txtmessage.clear

        port = self.lineport.text()
        ttl = self.linebrate.text()

        if(port != "" and ttl != ""):
            try :
                f=Finger(port,ttl,self.linelocation.text() ,self.linepoid.text(),self.lineamount.text())  

                self.txtmessage.clear
                self.txtmessage.setText("Scan finger print")
                time.sleep(2)
                
                # print("MainWindow")
                
                
                

                
                if (str(f.match) != "-1"):
                  

                    self.txtmessage.setText("Finger value:"+str(f.match()))
                    # msg = QtWidgets.QMessageBox()
                    # msg.setIcon(QtWidgets.QMessageBox.Information)
                    # msg.setText("Success")
                    # msg.setInformativeText('Fingerprint verified')
                    # msg.setWindowTitle("Finger Found at:"+str(f.match()))
                    # msg.exec_()
            except Exception as err:
                self.txtmessage.setText("Error Encountered \n"+str(err))
        # elif (self.linelocation.text() ==  ""):
        #     self.txtmessage.setText("Enter Location")
        # elif (self.linepoid.text() ==  ""):
        #     self.txtmessage.setText("Enter Pos ID")
        # elif (self.lineamount.text() ==  ""):
        #     self.txtmessage.setText("Enter Amount")

        else:
            self.txtmessage.setText("fill in com port and baud rate clear\n eg /dev/ttyUSB0 ")
    def delete(self):
        port = self.lineport.text()
        ttl = self.linebrate.text()
        
        try :
            f=Finger(port,ttlm,0,0,0)  
            if self.linefrom.text() != "" and self.lineto.text() != "" :
                fid=self.linefrom.text()
                n=self.lineto.text()
                f.delete(fid,n)
                self.txtmessage.setText(" Fingerprint(s) Successfully Deleted ")
            else :
                self.txtmessage.setText("fill in from and to sections to clear")

        except Exception as err:
                self.txtmessage.setText("Error Encountered \n"+str(err))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
